In [ ]:
!pip install sklearn

In [21]:

from sklearn.datasets import load_iris
import pandas as pd

  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.
  
  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
  
  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]
  
  note: This error originates from a subpr

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


In [11]:
#Load datasets
iris = load_iris()
X = iris.data
y = iris.target

In [12]:
display(X)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
display(y)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
#Convert Array to  DAtaFrame for Easier manipulation
iris_df = pd.DataFrame(data=X,columns = iris.feature_names)
iris_df['target'] = y
display(iris_df.head())
display(iris_df.shape)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

(150, 5)

In [24]:
from sklearn.model_selection import train_test_split
#Split the datasets into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=42)

In [25]:
X_train
X_train.shape

(120, 4)

In [30]:
#Scale the features
#Scaling is a preprocessing technique, which bringsd values in a specific range
#like [-1,1], which basicALLY improves accuracy
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [31]:
X_train_scaled

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.

In [39]:
from sklearn.neighbors import KNeighborsClassifier
#Initialize the kNN Classifier withnk=3
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
#fit the model
knn.fit(X_train_scaled,y_train)
#Make Predictions
y_pred = knn.predict(X_test_scaled)

In [49]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

#Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

#Display confusion matrix
conf_matrix = confusion_matrix(y_test,y_pred)
print("Confussion; ",conf_matrix)

#Classifier report
class_report = classification_report(y_test,y_pred)
print("Classification Report", class_report)

Accuracy: 0.97
Confussion;  [[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
Classification Report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      1.00      0.95         9
           2       1.00      0.91      0.95        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [56]:
data_cleaned = pd.read_csv("data_cleaned.csv")

In [57]:
data_cleaned

Survived        Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0           0  22.000000   7.2500         0         0         1           0   
1           1  38.000000  71.2833         1         0         0           1   
2           1  26.000000   7.9250         0         0         1           1   
3           1  35.000000  53.1000         1         0         0           1   
4           0  35.000000   8.0500         0         0         1           0   
..        ...        ...      ...       ...       ...       ...         ...   
886         0  27.000000  13.0000         0         1         0           0   
887         1  19.000000  30.0000         1         0         0           1   
888         0  29.699118  23.4500         0         0         1           1   
889         1  26.000000  30.0000         1         0         0           0   
890         0  32.000000   7.7500         0         0         1           0   

     Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0           1        0        1  ...        1        0        0        0   
1           0        0        1  ...        1        0        0        0   
2           0        1        0  ...        1        0        0        0   
3           0        0        1  ...        1        0        0        0   
4           1        1        0  ...        1        0        0        0   
..        ...      ...      ...  ...      ...      ...      ...      ...   
886         1        1        0  ...        1        0        0        0   
887         0        1        0  ...        1        0        0        0   
888         0        0        1  ...        0        0        1        0   
889         1        1        0  ...        1        0        0        0   
890         1        1        0  ...        1        0        0        0   

     Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0          0        0        0           0           0           1  
1          0        0        0           1           0           0  
2          0        0        0           0           0           1  
3          0        0        0           0           0           1  
4          0        0        0           0           0           1  
..       ...      ...      ...         ...         ...         ...  
886        0        0        0           0           0           1  
887        0        0        0           0           0           1  
888        0        0        0           0           0           1  
889        0        0        0           1           0           0  
890        0        0        0           0           1           0  

[891 rows x 25 columns]

In [67]:
y = data_cleaned.Survived
X = data_cleaned.drop("Survived", axis=1)

Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  Sex_male  \
0    22.000000   7.2500         0         0         1           0         1   
1    38.000000  71.2833         1         0         0           1         0   
2    26.000000   7.9250         0         0         1           1         0   
3    35.000000  53.1000         1         0         0           1         0   
4    35.000000   8.0500         0         0         1           0         1   
..         ...      ...       ...       ...       ...         ...       ...   
886  27.000000  13.0000         0         1         0           0         1   
887  19.000000  30.0000         1         0         0           1         0   
888  29.699118  23.4500         0         0         1           1         0   
889  26.000000  30.0000         1         0         0           0         1   
890  32.000000   7.7500         0         0         1           0         1   

     SibSp_0  SibSp_1  SibSp_2  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0          0        1        0  ...        1        0        0        0   
1          0        1        0  ...        1        0        0        0   
2          1        0        0  ...        1        0        0        0   
3          0        1        0  ...        1        0        0        0   
4          1        0        0  ...        1        0        0        0   
..       ...      ...      ...  ...      ...      ...      ...      ...   
886        1        0        0  ...        1        0        0        0   
887        1        0        0  ...        1        0        0        0   
888        0        1        0  ...        0        0        1        0   
889        1        0        0  ...        1        0        0        0   
890        1        0        0  ...        1        0        0        0   

     Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0          0        0        0           0           0           1  
1          0        0        0           1           0           0  
2          0        0        0           0           0           1  
3          0        0        0           0           0           1  
4          0        0        0           0           0           1  
..       ...      ...      ...         ...         ...         ...  
886        0        0        0           0           0           1  
887        0        0        0           0           0           1  
888        0        0        0           0           0           1  
889        0        0        0           1           0           0  
890        0        0        0           0           1           0  

[891 rows x 24 columns]

In [66]:
#importing the MinMax Scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [76]:
x_train, x_test, Y_train, Y_test = train_test_split(X,y, test_size =0.2, random_state = 56, stratify = y)

In [87]:
from sklearn.neighbors import KNeighborsClassifier as KNNalg
from sklearn.metrics import f1_score as f1

In [88]:
from sklearn.neighbors import KNeighborsClassifier
#Initialize the kNN Classifier withnk=3
k = 10
KNN = KNNalg(n_neighbors=k)
#fit the model
KNN.fit(x_train,Y_train)
#Make Predictions
y_pred = KNN.predict(x_test)

In [89]:
y_pred.shape

(179,)

In [93]:
acu = accuracy_score(Y_test, y_pred)
#predicting over the Train Set and Calcutating F1
k = f1(y_pred,Y_test)
k

0.5565217391304348

In [83]:
conf = confusion_matrix(Y_test, y_pred)

In [94]:
acu

0.7150837988826816

In [104]:
wq = pd.read_csv("winequality-white.csv", sep=";")

In [105]:
wq

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [107]:
yy = wq.quality
XX = wq.drop("quality",axis=1)

In [111]:
XX_train, XX_test, yy_train, yy_test = train_test_split(XX,yy, test_size =0.2, random_state = 56)

In [124]:
k = 20
kN = KNNalg(n_neighbors=k)

In [125]:
kN.fit(XX_train,yy_train)

KNeighborsClassifier(n_neighbors=20)

In [126]:
yy_pred = kN.predict(XX_test)

In [132]:
yy_pred.shape

(980,)

In [133]:
XX_test.shape

(980, 11)

In [128]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report
accuracy = accuracy_score(yy_test,yy_pred)

In [134]:
accuracy

46.02040816326531

In [130]:
conf = confusion_matrix(yy_test,yy_pred)
conf

array([[  0,   0,   2,   2,   0,   0,   0],
       [  0,   0,  23,  19,   0,   0,   0],
       [  0,   3, 123, 146,  13,   0,   0],
       [  0,   0, 109, 303,  33,   0,   0],
       [  0,   0,  23, 120,  25,   0,   0],
       [  0,   0,   8,  25,   2,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0]], dtype=int64)

In [20]:
clas =classification_report(yy_test,yy_pred)
print(clas)


NameError: name 'classification_report' is not defined

In [2]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Sample data
data = np.array([[1, 2], [2, 0], [0, 10]])

# Create MinMaxScaler instance
scaler = MinMaxScaler()

# Fit and transform the data
scaled_data = scaler.fit_transform(data)
print(data)
print(scaled_data)

[[ 1  2]
 [ 2  0]
 [ 0 10]]
[[0.5 0.2]
 [1.  0. ]
 [0.  1. ]]


In [4]:
from sklearn.preprocessing import LabelEncoder
labels = ['cat', 'dog', 'cat', 'bird']

# Create LabelEncoder instance
encoder = LabelEncoder()

# Fit and transform the labels
encoded_labels = encoder.fit_transform(labels)

print(labels)
print(encoded_labels)  # Output might be [0, 1, 0, 2] (order can vary)

['cat', 'dog', 'cat', 'bird']
[1 2 1 0]


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , f1_score,precision_score
# Sample dataset
data = {
    'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red', 'Green', 'Red'],
    'Size': ['S', 'M', 'M', 'S', 'L', 'L', 'M'],
    'Feature1': [1.0, 2.0, 1.5, 2.5, 1.1, 2.1, 1.3],
    'Target': ['A', 'A', 'B', 'B', 'A', 'A', 'B']
}

# Create a DataFrame
df = pd.DataFrame(data)

# Convert categorical data to numerical using LabelEncoder
label_encoder_color = LabelEncoder()
label_encoder_size = LabelEncoder()
label_encoder_target = LabelEncoder()

df['Color'] = label_encoder_color.fit_transform(df['Color'])
df['Size'] = label_encoder_size.fit_transform(df['Size'])
df['Target'] = label_encoder_target.fit_transform(df['Target'])

# Features and target variable
X = df[['Color', 'Size', 'Feature1']]  # Features
y = df['Target']                        # Target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create and apply StandardScaler to scale numerical features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the Decision Tree model
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train_scaled, y_train)

# Make predictions
y_pred = dt_classifier.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_pred, y_test)
print(f'Accuracy: {accuracy:.2f}')
f1 = f1_score(y_test,y_pred)
print(f'F1 Score: {f1: .2f}')
ps = precision_score(y_test,y_pred)
print(f'Percision Score: {ps: .2f}')

Accuracy: 0.33
F1 Score:  0.00
Percision Score:  0.00
