In [55]:
#TAsk 2 by mySelf
import numpy as np

In [56]:
input = [[2,3,4],
                  [3,4,5],
                  [5,6,7]]

weights = { 'node_1_1': np.array([1,1,1]),
           'node_1_2': np.array([1,2,-1]),
           'node_1_3': np.array([3,-2,1]),
           'node_1_4': np.array([1,-1,-1]),
           'node_2_1': np.array([2,1,2,1]),
           'node_2_2': np.array([1,2,-1,2]),
           'node_2_3': np.array([1,-2,1,-2]),
           'node_2_4': np.array([1,-1,-1,1]),
           'output' : np.array([1,3,2,1])
}

def relu(input):
    output = max(0,input)
    return output

In [57]:
def predict_with_network(input_data, weights):
    # Calculate node 1 in the first hidden layer
    node_1_1_input = (input_data * weights['node_1_1']).sum()
    node_1_1_output = relu(node_1_1_input)

    # Calculate node 2 in the first hidden layer
    node_1_2_input = (input_data * weights['node_1_2']).sum()
    node_1_2_output = relu(node_1_2_input)

    # Calculate node 3 in the first hidden layer
    node_1_3_input = (input_data * weights['node_1_3']).sum()
    node_1_3_output = relu(node_1_3_input)

    # Calculate node 4 in the first hidden layer
    node_1_4_input = (input_data * weights['node_1_4']).sum()
    node_1_4_output = relu(node_1_4_input)

    # Put node values into array: hidden_1_outputs
    hidden_1_outputs = np.array([node_1_1_output, node_1_2_output, node_1_3_output, node_1_4_output])

        # Calculate node 1 in the Second hidden layer
    node_2_1_input = (hidden_1_outputs * weights['node_2_1']).sum()
    node_2_1_output = relu(node_2_1_input)

    # Calculate node 2 in the Second  hidden layer
    node_2_2_input = (hidden_1_outputs * weights['node_2_2']).sum()
    node_2_2_output = relu(node_2_2_input)

    # Calculate node 3 in the Second  hidden layer
    node_2_3_input = (hidden_1_outputs * weights['node_2_3']).sum()
    node_2_3_output = relu(node_2_3_input)

    # Calculate node 4 in the Second  hidden layer
    node_2_4_input = (hidden_1_outputs * weights['node_2_4']).sum()
    node_2_4_output = relu(node_2_4_input)

    # Put node values into array: hidden_2_outputs
    hidden_2_outputs = np.array([node_2_1_output, node_2_2_output, node_2_3_output, node_2_4_output])
    
    # Calculate output here: model_output
    model_output = (hidden_2_outputs * weights['output']).sum()
    
    # Return model_output
    return(model_output)

In [58]:
predict_with_network(input[0],weights)

80

In [59]:
predict_with_network(input[1],weights)

108

In [60]:
predict_with_network(input[2],weights)

166

In [61]:
#Throw ChatGPT
import numpy as np

# Define the ReLU activation function
def relu(input):
    return np.maximum(0, input)

# Inputs
input_data = np.array([[2, 3, 4],
                       [3, 4, 5],
                       [5, 6, 7]])

# Weights for all layers
weights = {
    'node_1_1': np.array([1, 1, 1]),
    'node_1_2': np.array([1, 2, -1]),
    'node_1_3': np.array([3, -2, 1]),
    'node_1_4': np.array([1, -1, -1]),
    'node_2_1': np.array([2, 1, 2, 1]),
    'node_2_2': np.array([1, 2, -1, 2]),
    'node_2_3': np.array([1, -2, 1, -2]),
    'node_2_4': np.array([1, -1, -1, 1]),
    'output': np.array([1, 3, 2, 1])
}

# --- First Layer (Hidden Layer 1) ---
# Compute inputs for each node in the first hidden layer
node_1_1_input = np.dot(input_data, weights['node_1_1'])
node_1_2_input = np.dot(input_data, weights['node_1_2'])
node_1_3_input = np.dot(input_data, weights['node_1_3'])
node_1_4_input = np.dot(input_data, weights['node_1_4'])

# Apply ReLU activation function
node_1_1_output = relu(node_1_1_input)
node_1_2_output = relu(node_1_2_input)
node_1_3_output = relu(node_1_3_input)
node_1_4_output = relu(node_1_4_input)

# Combine hidden layer 1 outputs
hidden_layer_1_output = np.column_stack((node_1_1_output, node_1_2_output, node_1_3_output, node_1_4_output))

# --- Second Layer (Hidden Layer 2) ---
# Compute inputs for each node in the second hidden layer
node_2_1_input = np.dot(hidden_layer_1_output, weights['node_2_1'])
node_2_2_input = np.dot(hidden_layer_1_output, weights['node_2_2'])
node_2_3_input = np.dot(hidden_layer_1_output, weights['node_2_3'])
node_2_4_input = np.dot(hidden_layer_1_output, weights['node_2_4'])

# Apply ReLU activation function
node_2_1_output = relu(node_2_1_input)
node_2_2_output = relu(node_2_2_input)
node_2_3_output = relu(node_2_3_input)
node_2_4_output = relu(node_2_4_input)

# Combine hidden layer 2 outputs
hidden_layer_2_output = np.column_stack((node_2_1_output, node_2_2_output, node_2_3_output, node_2_4_output))

# --- Output Layer ---
# Compute input for the output node
output_input = np.dot(hidden_layer_2_output, weights['output'])

# Apply ReLU activation function (if needed)
final_output = relu(output_input)

# Print Results
print("Hidden Layer 1 Outputs:\n", hidden_layer_1_output)
print("Hidden Layer 2 Outputs:\n", hidden_layer_2_output)
print("Final Output:\n", final_output)


Hidden Layer 1 Outputs:
 [[ 9  4  4  0]
 [12  6  6  0]
 [18 10 10  0]]
Hidden Layer 2 Outputs:
 [[30 13  5  1]
 [42 18  6  0]
 [66 28  8  0]]
Final Output:
 [ 80 108 166]
